(function(){'use strict';
  const DATA=window.RESEARCH_DATA||{packages:[]};
  const norm=s=>(s||'').toString().replace(/\s+/g,' ').trim();
  const safeUrl=u=>{u=norm(u);return /^(https:\/\/|mailto:|tel:)/i.test(u)?u:'#'};
  const params=new URLSearchParams(location.search);
  const packages=()=>Array.isArray(DATA.packages)?DATA.packages:[];
  const countSections=()=>packages().reduce((n,p)=>n+((p.sections||[]).length),0);
  const countBots=()=>packages().reduce((n,p)=>n+(p.sections||[]).reduce((m,s)=>m+((s.bots||[]).length),0),0);
  const findPackage=()=>{const id=params.get('package')||params.get('pkg');return packages().find(p=>p.id===id)||packages()[0]||null};
  const findSection=()=>{const sid=params.get('section')||params.get('sec');for(const p of packages()){const s=(p.sections||[]).find(x=>x.id===sid);if(s)return {package:p,section:s}}const p=findPackage();return p&&p.sections&&p.sections[0]?{package:p,section:p.sections[0]}:null};
  const botItems=()=>packages().flatMap(p=>(p.sections||[]).flatMap(s=>(s.bots||[]).map(b=>({package:p,section:s,bot:b}))));
  window.DataService={DATA,norm,safeUrl,params,packages,countSections,countBots,findPackage,findSection,botItems};
})();